mutation AddRoute ($name: String!, $type: String!, $miles: Float!, $startingElevation: Int!, $finalElevation: Int, $iframeData: String!){
    createRoute (
        name: $name,
        type: $type,
        miles: $miles,
        startingElevation: $startingElevation,
        finalElevation: $finalElevation,
        iframeData: $iframeData
    ) {
        id
    }
}
