mutation AddRoute ($id: String!, $name: String!, $type: String!, $miles: Float!, $startPoint: String!, $endPoint: String!, $startingElevation: Int!, $finalElevation: Int, $iframeData: String!){
updateOneRoute (
    where: { 
        id: $id
	},
    data: {
    name: $name,
    type: $type,
    miles: $miles,
    startPoint: $startPoint,
    endPoint: $endPoint,
    startingElevation: $startingElevation,
    finalElevation: $finalElevation,
    iframeData: $iframeData
    }
  ) 
  {
    id,
  }
}